services:
  frontend:
    build: ../frontend
    volumes:
      - ../frontend:/app
    working_dir: /app
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    networks:
      - sail
    command: sh -c "sleep infinity"
